language: php

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=4.0.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --dev --no-interaction

script:
   - phpunit --testsuite=Unit
